# Generated by Django 3.1.1 on 2020-09-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=50)),
                ('zips', models.IntegerField()),
            ],
        ),
    ]
